// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD89Q_fGnFYdyTJaDOAbz-VffkkBDCZv3s',
    appId: '1:848135561725:web:5f6e4e449a5451fdd77994',
    messagingSenderId: '848135561725',
    projectId: 'recipe-maker-19922',
    authDomain: 'recipe-maker-19922.firebaseapp.com',
    storageBucket: 'recipe-maker-19922.appspot.com',
    measurementId: 'G-N4NVGDHNZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByOU8vM0zM00uv8A-unFCMELWnu2BpC8c',
    appId: '1:848135561725:android:83fb871c5e915e6dd77994',
    messagingSenderId: '848135561725',
    projectId: 'recipe-maker-19922',
    storageBucket: 'recipe-maker-19922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu7wLBIsCujAV8itp0-omggI_QoxBn9pc',
    appId: '1:848135561725:ios:217324ebc8742f56d77994',
    messagingSenderId: '848135561725',
    projectId: 'recipe-maker-19922',
    storageBucket: 'recipe-maker-19922.appspot.com',
    iosBundleId: 'com.example.ac7',
  );
}
